/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tw.cn.cap.gtb.todo;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void should_list_existing_tasks() throws IOException {
        List<String> result = new App().run();
        Assertions.assertEquals(List.of("#To Be Done","1 task 01","2 task 02",
                "#Completed","3 task 03","4 task 04"), result);
    }
}
